name: arich_sample
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hooks_riverpod: ^1.0.4
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  flutter_hooks: ^0.18.5+1
  firebase_core: ^1.20.0
  cloud_firestore: ^3.4.3
  firebase_auth: ^3.6.2
  shared_preferences: ^2.0.15
  settings_ui: ^2.0.2
  auto_route: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  grinder: ^0.9.2
  auto_route_generator: ^4.2.0
flutter:

  uses-material-design: true

